config/routes.rb
Rails.application.routes.draw do
  
  get "/", to: "welcome#index", as: :root
  post "/", to: "welcome#create", as: false
  get "/delete/:id", to: "welcome#delete", as: :delete
  
  get "/user/:id", to: "user#show", as: :show


end

app/models/familia.rb
class Familia < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find params[:id]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @familia = Familia.all
    @membro = User.new
  end

  def create
    @membro = User.create(user_params)
    @friend = Familia.order("RANDOM()").first


    if @friend.name == @membro.name
      render :create      
    else
      @membro.friend = @friend.name
      if @membro.save

        Familia.find_by_name(@membro.friend).delete
        redirect_to show_path(@membro.id)
      else
        redirect_to root_path
      end  
    end

  end

  def delete
    @membro = User.find params[:id]
    @membro.delete

    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :password,
      :password_confirmation,
      :friend
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmigoSecreto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/show.html.erb
<h1><%= @user.name %></h1>

<p>Seu amigo secreto é: <h1><%= @user.friend %></h1></p>

<h1><%= link_to "OK", delete_path(@user.id) %></h1>

app/views/welcome/index.html.erb
<h1>Amigo secreto</h1>

<h2 style="color:red;">REGRAS:</h2>

<ol>
  <li>Cada pessoa só podera criar uma conta.</li>
  <li style="color: red; font-size: 20px;">O nome do seu amigo aparecera apenas 1 vez, depois a conta sera deletada</li>
  <li>Não deixe ninguem mais alem de você ver o monitor</li>
  <li style="color: red; font-size: 20px;">Clique no OK depois que o nome do seu amigo aparecer</li>
</ol>

<h3 style="color: green;">
  Pode ser que você volte a essa tela antes de ver o nome do seu amigo,<br>
  caso isso aconteça podera ser pelos seguinte acontecimentos: (em ambos os casos, tente novamente)
</h3>
<ul>
  <li>As senha não são iguais.</li>
  <li>Você retirou seu própio nome</li>
</ul>


<%= form_for @membro, url: root_path do |membro| %>
  <p>
    <%= membro.label :name, "Nome" %>
    <%= membro.text_field :name %>
  </p>

  <p>
    <%= membro.label :password, "Senha" %>
    <%= membro.password_field :password %>
  </p>

  <p>
    <%= membro.label :password_confirmation, "Confirmar senha" %>
    <%= membro.password_field :password_confirmation %>
  </p>

  <%= membro.submit %>


<% end %>